# 服务配置，配置IP、端口等
server:
  host: 0.0.0.0 # 如需要任意IP访问，则填写:“0.0.0.0” 或 “::”
  port: 21080 # 如果随机生成，则填写:“0”
  context: / # 如直接通过IP+端口访问，则填写:“” 或 “/”
  data: ./data # 数据存储目录，存储文件等
  tls:
    open: false # 是否开启 https 默认关闭 建议开启后使用 https 访问
    cert: ./conf/server.crt  # 证书
    key: ./conf/server.key   # 证书 密钥

# 日志配置
log:
  filename: ./log/server.log
  maxSize: 100 # 文件大小单位M
  maxAge: 7 # 保留多少天
  maxBackups: 10 # 最多几个文件
  level: debug # 级别，debug，info，warn，error

github:
  clientId:
  clientSecret:

# 日志数据 （操作日志，终端执行日志等） 保留天数，设置 0 永久保留
logDataSaveDays: 15
